language: csharp
sudo: required
dist: xenial

# dotnet: 3.1.103 
dotnet: 3.1.300
mono:
  - latest # => "stable release"
  - weekly # => "latest commits"
os:
  - linux

script:
  - ./build.sh

matrix:
  fast_finish: true
  allow_failures:
    - mono: weekly
